language: node_js
node_js:
- 0.1
env:
- TAG=v0.6.9.3
install:
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
- sudo tar zxvf $HOME/purescript.tar.gz -C /usr/local/bin purescript/psc{,i,-docs,-make}
  --strip-components=1
- sudo chmod a+x /usr/local/bin/psc{,i,-docs,-make}
- npm install bower gulp -g
- npm install && bower install --force
script:
- gulp deploy-prod
before_deploy:
- cp -r public slamdata
- tar cjf slamdata.tar.bz2 slamdata
deploy:
  provider: releases
  api-key:
    secure: WsPNt1CA/TeWXJfMXpvuCuED14XYGxJ9m8Fji/SxpT6ja3jjKIB6yKePu4NI1C7WZCK9qKegPWwzzk+MOJj/HKa72gQdQq7eLqliP3JF8GjP0KDNfpxd5kyc6Nelxq1UVy9N2JoaYM4PaQ2lZIo86Etw8v7jaCKj59+dKO6+ZH0=
  file: slamdata.tar.bz2
  skip_cleanup: true
  on:
    branch: wip/publish-release
notifications:
  irc:
    channels:
    - chat.freenode.net#slamdata
    template:
    - '%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}'
